name: GitHub Projects Automation

on:
  pull_request:
    types: [closed]

jobs:
  move-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Move issue to Done
        run: echo "Simulate moving issue to Done (e.g., via GitHub API)"